//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBweatherEntities : DbContext
    {
        public DBweatherEntities()
            : base("name=DBweatherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<Clouds> Clouds1 { get; set; }
        public virtual DbSet<Coord> Coords { get; set; }
        public virtual DbSet<Main> Mains { get; set; }
        public virtual DbSet<OpenWeather> OpenWeathers { get; set; }
        public virtual DbSet<Sys> Sys { get; set; }
        public virtual DbSet<Weather> Weathers { get; set; }
        public virtual DbSet<Wind> Winds { get; set; }
    }
}
