//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenWeather
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpenWeather()
        {
            this.Weather = new HashSet<Weather>();
        }
    
        public int idOpen { get; set; }
        public int idCoord { get; set; }
        public string @base { get; set; }
        public int idMain { get; set; }
        public int visibility { get; set; }
        public int idWind { get; set; }
        public int idClouds { get; set; }
        public int dt { get; set; }
        public int idSys { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public int cod { get; set; }
    
        public virtual Clouds Clouds { get; set; }
        public virtual Coord Coord { get; set; }
        public virtual Main Main { get; set; }
        public virtual Sys Sys { get; set; }
        public virtual Wind Wind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Weather> Weather { get; set; }
    }
}
