//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int idWeather { get; set; }
        public int id { get; set; }
        public string main { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
        public int idOpenWeather { get; set; }
    
        public virtual OpenWeather OpenWeather { get; set; }
    }
}
